//Copyright (c) 2026 Denys Dragunov, dragunovdenis@gmail.com
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files(the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and /or sell
//copies of the Software, and to permit persons to whom the Software is furnished
//to do so, subject to the following conditions :

//The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
//INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
//PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
//HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
//OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
//SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

namespace BAnalyzerCore.Ollama;

/// <summary>
/// Result of an attempt to retrieve the collection of the locally available models.
/// </summary>
public record ModelsResult(bool Available, IReadOnlyList<ModelInfo> Models, string Error);

/// <summary>
/// Description of a single locally available model.
/// </summary>
/// <param name="Name">Name of the model (the identifier accepted by the "/api/chat" end-point).</param>
/// <param name="Size">Size of the model on disk, in bytes, or "null" if not reported.</param>
/// <param name="ParameterSize">Human-readable parameter count, for example "8B", or "null" if not reported.</param>
/// <param name="QuantizationLevel">Quantization level, for example "Q4_K_M", or "null" if not reported.</param>
public sealed record ModelInfo(string Name, long? Size, string ParameterSize, string QuantizationLevel)
{
    /// <summary>
    /// Human-readable summary of the extra details (size, parameter count,
    /// quantization level), suitable for display next to the model name.
    /// Empty if none of the details were reported by the service.
    /// </summary>
    public string Description
    {
        get
        {
            var parts = new List<string>();

            if (Size is > 0)
                parts.Add($"{Size.Value * 1.0 / (1 << 30):0.#} GB");

            if (!string.IsNullOrWhiteSpace(ParameterSize))
                parts.Add(ParameterSize);

            if (!string.IsNullOrWhiteSpace(QuantizationLevel))
                parts.Add(QuantizationLevel);

            return string.Join(" · ", parts);
        }
    }

    /// <summary>
    /// Returns the name of the model, so that instances can be displayed or
    /// compared against plain model names without extra plumbing.
    /// </summary>
    public override string ToString() => Name;
}

/// <summary>
/// Declaration of a single parameter of a tool.
/// </summary>
/// <param name="Name">Name of the parameter.</param>
/// <param name="Type">JSON-schema type of the parameter ("string", "integer" etc.).</param>
/// <param name="Description">
/// Description of the parameter, used by the model to decide how to fill it in.
/// </param>
/// <param name="AllowedValues">
/// The values the parameter is allowed to take or "null" if it is unrestricted.
/// Restricting a parameter this way makes it impossible for the model to
/// produce an unsupported value in the first place, which is cheaper and more
/// reliable than validating the requests after the fact.
/// </param>
/// <param name="Required">Whether the parameter must be supplied.</param>
public sealed record ToolParameter(string Name, string Type, string Description,
    IReadOnlyList<string> AllowedValues = null, bool Required = true);

/// <summary>
/// Declaration of a tool that a model is allowed to call.
/// </summary>
/// <param name="Name">Name of the tool.</param>
/// <param name="Description">
/// Description of what the tool does, used by the model to decide whether the
/// tool is relevant to the request at hand.
/// </param>
/// <param name="Parameters">Parameters the tool accepts.</param>
public sealed record ToolDefinition(string Name, string Description,
    IReadOnlyList<ToolParameter> Parameters);

/// <summary>
/// A single portion of an answer that is being generated by a model.
/// </summary>
/// <param name="Content">Portion of the answer (can be empty).</param>
/// <param name="Thinking">Portion of the "reasoning" that precedes the answer (can be empty).</param>
/// <param name="ToolCalls">
/// Tools the model has decided to call (can be "null"). Note that the service
/// reports a tool call in a chunk with the "done" flag <b>not</b> set and then
/// terminates the stream with the same "stop" reason an ordinary answer ends
/// with. There is therefore no terminator to branch on: the consumers must
/// collect the tool calls from all the chunks and decide what to do once the
/// stream is over.
/// </param>
public readonly record struct ChatChunk(string Content, string Thinking,
    IReadOnlyList<ToolCall> ToolCalls = null);

/// <summary>
/// Capabilities of a model, as reported by the Ollama service.
/// </summary>
public readonly record struct ModelCaps(int ContextWindow, bool Thinking, 
    bool Completion, bool Vision, bool Tools);

/// <summary>
/// Interface of a client of the local Ollama service.
/// </summary>
/// <remarks>
/// Implementations must never throw: all the failures are supposed to be
/// reported through the corresponding fields of the returned records. The only
/// exception to this rule is <see cref="IOllamaClient.ChatStreamAsync"/> (see the remarks there).
/// </remarks>
public interface IOllamaClient : IDisposable
{
    /// <summary>
    /// Returns names of the models that are available locally. Doubles as a
    /// "health check" of the service: <see cref="ModelsResult.Available"/> is
    /// "false" if the service could not be reached.
    /// </summary>
    Task<ModelsResult> TryGetModelsAsync(CancellationToken ct);

    /// <summary>
    /// Returns capabilities of the model with the given <paramref name="model"/> name.
    /// </summary>
    Task<ModelCaps?> GetModelCapsAsync(string model, CancellationToken ct);

    /// <summary>
    /// Returns "true" if the model with the given name declares the "tools" capability.
    /// </summary>
    Task<bool> SupportsToolsAsync(string model, CancellationToken ct);

    /// <summary>
    /// Sends the given <paramref name="history"/> to the model with the given
    /// <paramref name="model"/> name and returns the answer in portions, as it
    /// is being generated.
    /// </summary>
    /// <param name="model">Name of the model to run the conversation with.</param>
    /// <param name="history">The conversation so far.</param>
    /// <param name="tools">
    /// Tools the model is allowed to call, or "null" if it must answer on its
    /// own. Must be left "null" for the models that do not declare the
    /// corresponding capability (see <see cref="SupportsToolsAsync"/>).
    /// </param>
    /// <param name="ct">Cancellation token.</param>
    /// <remarks>
    /// Unlike the other members of the interface, this one <b>does throw</b> on
    /// failure: the language does not allow "yield return" within a "try/catch"
    /// block, so an iterator can't report the failures through its return value.
    /// The callers are supposed to handle the exceptions themselves.
    /// </remarks>
    IAsyncEnumerable<ChatChunk> ChatStreamAsync(string model,
        IReadOnlyList<ChatMessage> history, IReadOnlyList<ToolDefinition> tools,
        CancellationToken ct);
}
